
project_id = "tfmlretexydslgowlkid"

[global.env]
# These are environment variables shared across all functions
GROK3_API_KEY = "CHANGEME"

[[functions]]
name = "agent-network-coordinator"
verify_jwt = false
