
# Supabase Edge Function Config

project_id = "tfmlretexydslgowlkid"

[functions.fetch-crypto-prices]
verify_jwt = false

[functions.portfolio-decision]
verify_jwt = false

[functions.crypto-price-data]
verify_jwt = false

[functions.market-data-collector]
verify_jwt = false

[functions.fetch-market-data]
verify_jwt = false

[functions.quantum-portfolio]
verify_jwt = false
