
project_id = "tfmlretexydslgowlkid"
# This is a basic configuration for Supabase Edge Functions
# Each function configuration is defined as a separate [[functions]] object

[[functions]]
name = "real-crypto-data"
verify_jwt = false
