
# Supabase Edge Functions configuration
project_id = "tfmlretexydslgowlkid"

[functions.log-api-call]
verify_jwt = false

[functions.log-transaction-audit]
verify_jwt = false

[functions.submit-kyc]
verify_jwt = false

[functions.deepseek-response]
verify_jwt = false

[functions.generate-advice]
verify_jwt = false

