
# Supabase Edge Functions configuration
project_id = "tfmlretexydslgowlkid"

[functions.log-api-call]
verify_jwt = false

[functions.log-transaction-audit]
verify_jwt = false

[functions.verify-2fa]
verify_jwt = false

[functions.send-2fa-code]
verify_jwt = false

[functions.deepseek-response]
verify_jwt = false

[functions.claude-response]
verify_jwt = false

[functions.gemini-response]
verify_jwt = false

[functions.grok3-response]
verify_jwt = false

[functions.generate-trading-advice]
verify_jwt = false

[functions.generate-advice]
verify_jwt = false
