
project_id = "tfmlretexydslgowlkid"

[functions.process-voice]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.generate-ai-response]
verify_jwt = false

[functions.generate-trading-advice]
verify_jwt = false
