
project_id = 'your-project-id'

[api]
# Port to use for the API URL.
port = 54321
# Enable JWT verification for API requests.
verify_jwt = false

[[edge_functions]]
name = "grok3-response"
path = "supabase/functions/grok3-response"
verify_jwt = false

[[edge_functions]]
name = "generate-ai-response"
path = "supabase/functions/generate-ai-response"
verify_jwt = false

[[edge_functions]]
name = "openai-response"
path = "supabase/functions/openai-response"
verify_jwt = false

[[edge_functions]]
name = "claude-response"
path = "supabase/functions/claude-response"
verify_jwt = false

[[edge_functions]]
name = "gemini-response"
path = "supabase/functions/gemini-response"
verify_jwt = false
