
# This is the project configuration for Supabase
project_id = 'your-project-id'

[api]
# Port to use for the API URL.
port = 54321

[functions]
[functions.grok3-response]
verify_jwt = false

[functions.generate-ai-response]
verify_jwt = false

[functions.openai-response]
verify_jwt = false

[functions.claude-response]
verify_jwt = false

[functions.gemini-response]
verify_jwt = false

[functions.deepseek-response]
verify_jwt = false
