
project_id = "tfmlretexydslgowlkid"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
port = 54323

[functions.deepseek-response]
verify_jwt = false

[functions.openai-response]
verify_jwt = false

[functions.claude-response]
verify_jwt = false

[functions.gemini-response]
verify_jwt = false

[functions.grok3-response]
verify_jwt = false
