
# This is the project configuration for Supabase
project_id = 'your-project-id'

[api]
# Port to use for the API URL.
port = 54321

[functions]
[functions.grok3-response]
path = "supabase/functions/grok3-response"

[functions.generate-ai-response]
path = "supabase/functions/generate-ai-response"

[functions.openai-response]
path = "supabase/functions/openai-response"

[functions.claude-response]
path = "supabase/functions/claude-response"

[functions.gemini-response]
path = "supabase/functions/gemini-response"
