
project_id = "tfmlretexydslgowlkid"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
port = 54323

[[functions]]
name = "deepseek-response"
verify_jwt = false
