
project_id = "tfmlretexydslgowlkid"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[realtime]
enabled = true

[functions]
[functions.trading-analysis]
verify_jwt = false
