
import { useState, useEffect } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { useToast } from "@/hooks/use-toast";
import { useAgentNetwork } from "@/hooks/use-agent-network";
import { Brain, RefreshCw, Network, ExternalLink } from "lucide-react";
import { AI_MODELS, ModelId } from "@/components/chat/types/GrokSettings";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible";

interface CollaborativeInsightsPanelProps {
  currentData?: any;
}

export function CollaborativeInsightsPanel({ currentData }: CollaborativeInsightsPanelProps) {
  const { toast } = useToast();
  const { 
    isInitialized, 
    isLoading, 
    activeAgents, 
    lastAnalysis, 
    generateAnalysis 
  } = useAgentNetwork();
  
  const [selectedModel, setSelectedModel] = useState<ModelId>('grok3');
  const [showAgents, setShowAgents] = useState(false);
  
  useEffect(() => {
    // Generate initial analysis when component mounts
    if (isInitialized && !lastAnalysis) {
      handleGenerateInsights();
    }
  }, [isInitialized, lastAnalysis]);
  
  const handleGenerateInsights = async () => {
    try {
      await generateAnalysis(currentData, selectedModel);
      toast({
        title: "Insights Generated",
        description: "Collaborative trading insights have been updated.",
        duration: 3000,
      });
    } catch (error) {
      console.error("Error generating insights:", error);
      toast({
        title: "Generation Failed",
        description: "Could not generate collaborative insights. Please try again.",
        variant: "destructive",
      });
    }
  };
  
  const handleModelChange = (value: string) => {
    setSelectedModel(value as ModelId);
  };
  
  return (
    <Card className="backdrop-blur-xl bg-secondary/10 border border-white/10 shadow-[0_4px_12px_-2px_rgba(0,0,0,0.3)]">
      <CardHeader className="flex flex-row items-center justify-between pb-2">
        <CardTitle className="text-xl font-bold flex items-center">
          <Brain className="w-5 h-5 mr-2" /> Collaborative AI Insights
        </CardTitle>
        <div className="flex items-center gap-2">
          <Button 
            variant="ghost" 
            size="icon"
            onClick={() => setShowAgents(!showAgents)}
          >
            <Network className="h-4 w-4" />
          </Button>
          <Button
            variant="outline"
            size="sm"
            onClick={handleGenerateInsights}
            disabled={isLoading}
            className="flex items-center gap-1"
          >
            <RefreshCw className={`h-3 w-3 ${isLoading ? 'animate-spin' : ''}`} />
            <span>Refresh</span>
          </Button>
        </div>
      </CardHeader>
      
      <CardContent className="space-y-4">
        <Tabs defaultValue="insights">
          <TabsList className="grid w-full grid-cols-2">
            <TabsTrigger value="insights">Insights</TabsTrigger>
            <TabsTrigger value="settings">Settings</TabsTrigger>
          </TabsList>
          
          <TabsContent value="insights" className="space-y-4 mt-4">
            {isLoading ? (
              <div className="flex flex-col items-center justify-center py-8 space-y-4">
                <div className="animate-spin h-8 w-8 border-2 border-primary rounded-full border-t-transparent"></div>
                <p className="text-sm text-muted-foreground">Gathering collaborative insights...</p>
              </div>
            ) : lastAnalysis ? (
              <div className="prose prose-sm dark:prose-invert max-w-none">
                <div className="text-sm whitespace-pre-line">{lastAnalysis}</div>
                
                <div className="mt-4 text-xs text-muted-foreground">
                  <div className="flex items-center gap-1 mb-2">
                    <Network className="h-3 w-3" />
                    <span>Generated by {activeAgents.length} collaborating AI agents</span>
                  </div>
                  
                  <Collapsible open={showAgents} onOpenChange={setShowAgents}>
                    <CollapsibleTrigger asChild>
                      <Button variant="link" className="h-auto p-0 text-xs">
                        {showAgents ? 'Hide contributing agents' : 'Show contributing agents'}
                      </Button>
                    </CollapsibleTrigger>
                    <CollapsibleContent className="mt-2">
                      <div className="grid grid-cols-2 gap-2">
                        {activeAgents.map(agent => (
                          <div key={agent.id} className="text-xs bg-muted/50 p-2 rounded flex items-center gap-1">
                            <div className={`w-2 h-2 rounded-full ${agent.status === 'active' ? 'bg-green-500' : 'bg-gray-400'}`} />
                            {agent.name}
                          </div>
                        ))}
                      </div>
                    </CollapsibleContent>
                  </Collapsible>
                </div>
              </div>
            ) : (
              <div className="flex flex-col items-center justify-center py-8 space-y-4">
                <Brain className="h-12 w-12 text-muted-foreground" />
                <p className="text-muted-foreground">No insights generated yet</p>
                <Button onClick={handleGenerateInsights}>Generate Insights</Button>
              </div>
            )}
          </TabsContent>
          
          <TabsContent value="settings" className="space-y-4 mt-4">
            <div className="space-y-2">
              <label className="text-sm font-medium">Primary AI Model</label>
              <Select value={selectedModel} onValueChange={handleModelChange}>
                <SelectTrigger>
                  <SelectValue placeholder="Select a model" />
                </SelectTrigger>
                <SelectContent>
                  {AI_MODELS.map(model => (
                    <SelectItem key={model.id} value={model.id}>
                      {model.name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
              <p className="text-xs text-muted-foreground mt-1">
                This model will coordinate the collaborative analysis.
              </p>
            </div>
            
            <div className="pt-4 border-t">
              <Button 
                variant="outline" 
                size="sm" 
                className="w-full"
                asChild
              >
                <a href="/admin/agent-network" className="flex items-center justify-center gap-1">
                  <Network className="h-4 w-4" />
                  <span>Open Full Agent Network Dashboard</span>
                  <ExternalLink className="h-3 w-3 ml-1" />
                </a>
              </Button>
            </div>
          </TabsContent>
        </Tabs>
      </CardContent>
    </Card>
  );
}
